### ISSUE TITLE
Summer Semester Goals

### ISSUE THREAD

**Issue by readersm** [readersm/Master-s-Program#2]
- [ ] work with Zack on paper for Hort publication and proceedings of FSHS ASAP
- [x] finish final EDIS doc on Sunn Hemp edits and work with Ariel to clean up comments by July 7
- [ ] finish proposal draft by August 9 
     - [x] talk to Romain about layout ideas and process of writing
     - [x] make outline with sections and points to cover  
- [ ] set committee date for proposal overview (mid to late August)
- [ ] clean up all data sheets for analysis during Fall semester course (Intro to Applies Statistics)

**Comment by brymz** [comment]
This looks great Stacy. I'd like to get your FSHS presentation prepared for HortScience or HortTechnology and reprint in the proceedings. It would technically be due now, but we can make steady progress for ASAP. I think it would be good to set up a meeting with Tim to discuss his involvement and support of the effort.

**Comment by readersm** [comment]
Sounds good. Tim leaves for a week's vacation on Tuesday through the following Monday so I'll try to talk to him about it before then. If you'd like to zoom and be there too, I could see if he is available sometime Monday afternoon. Are you available at all Monday afternoon?

**Comment by brymz** [comment]
Ok. 1-2p or 3-4p on Mon. ~Z

**Comment by readersm** [comment]
1-2 pm it is! Here is the Zoom meeting invite:

Topic: Cover Crop Physiology first two seasons paper discussion
Time: Jul 1, 2019 01:00 PM Eastern Time (US and Canada)

Join Zoom Meeting
[https://us04web.zoom.us/j/219332736](url)

Meeting ID: 219 332 736

**Comment by brymz** [comment]
Got it. I have a site visit immediately before. I’ll send you a text if it is dragging on.
~Zack
