### ISSUE TITLE
BD and Weed data

### ISSUE THREAD

**Issue by readersm** [readersm/Master-s-Program#8]
Hey Zack,

Here's the pre experiment, post experiment BD ANOVA and figure. It's still showing significant increase in BD (not what we want) with cover cropping. Though they are still within normal (good) ranges for BD in sandy soils:

            Df   Sum Sq  Mean Sq F value  Pr(>F)   
CropTrt      5 0.006969 0.001394   1.701 0.28709   
Time         1 0.020008 0.020008  24.417 0.00432 **
Residuals    5 0.004097 0.000819                   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> print(HSD.test(aov_test, "Time")$groups)
       avg_BD groups
post 1.331944      a
pre  1.250278      b

![pre-post BD](https://user-images.githubusercontent.com/36899811/93726674-5e53e500-fb85-11ea-9352-a629147f4e17.png)

I looked through all of the weed data and Summer 2019 is the one that is making the t/ha so high. It was a grass seed that came up over the whole plot. It's the reason it took 3 days to harvest that season, because there was so much weed biomass. All of the sampling unit values within that season are accurate, but I do remember a lot of soil being with the roots of the grass though I did the same routine of beating off the soil each season. I added CpCycle to the ANOVA:

             Df Sum Sq Mean Sq F value   Pr(>F)    
RowNum        1  330.3   330.3  47.826 1.73e-10 ***
CpCycle       3 3003.8  1001.3 144.986  < 2e-16 ***
CropTrt       5   60.6    12.1   1.755    0.127    
Residuals   134  925.4     6.9                     
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> print(HSD.test(aov_weeds, "RowNum")$groups)
  avg_weeds_tha groups
1      8.620083      a
2      5.960403      b
3      4.905264     bc
5      4.685639     bc
4      4.213931     bc
6      3.315750      c
> print(HSD.test(aov_weeds, "CpCycle")$groups)
           avg_weeds_tha groups
Summer2019     12.459861      a
Summer2020      6.014676      b
Winter2019      1.593426      c
Winter2018      1.066083      c

From all of this, maybe it is good to keep the row-effect in my back pocket to explain why we calculated LER by row. And perhaps visualize the CpCycle effect as bellow? OR I could calculate the weed biomass as percent total on average and include the CC biomass. I don't think that would help explain anything that wouldn't come from the CpCycle bar graph. Thoughts?
![weeds](https://user-images.githubusercontent.com/36899811/93727408-fef7d400-fb88-11ea-96a7-f46f59e04e22.png)

**Comment by brymz** [comment]
I think this is good supplemental information to support your interpretation of the CropCycle and row effects. I recommend you keep it in the background until it’s specifically requested.

**Comment by readersm** [comment]
just wanted to updated you on what I did with these - There is no pre the whole experiment because we didn't decided to do BD until Winter 2019 (though I had already planted). I'm thinking of just keeping the second figure and ANOVA (I have both ANOVA tables built out)
![Pre-Post BD (1)](https://user-images.githubusercontent.com/36899811/94475347-f01eac00-019c-11eb-9a4b-1fb580d1b68d.png)
![BD over time](https://user-images.githubusercontent.com/36899811/94475350-f14fd900-019c-11eb-8382-eb9ec664da48.png)
